---
## Sources
# https://coderwall.com/p/0nckqg/ansible-reboot-ubuntu-if-needed

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 10
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: whoami
  become: true
  # when: reboot_required_file